//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсач
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int id_заказа { get; set; }
        public string Дата_исполнения { get; set; }
        public string Номер_Договора { get; set; }
        public Nullable<int> Клиент { get; set; }
        public string Дата_создания { get; set; }
        public Nullable<int> id_статус_заказов { get; set; }
        public Nullable<int> id_Услуги { get; set; }
    
        public virtual Исполнители Исполнители { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Статусы_заказов Статусы_заказов { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
